VERSION = "0.0.1"

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_RAYSPLIT = 1 # This is the divisor for raycasting, a larger number means more steps between rays

LEVEL_SIZE = 15
PATH_CHANCE = 95
PATH_DIRECTION_CHANCE = 50
CELL_SPACING = 10
PATH_OFFSET = 10
MINI_MAP_OFFSET = SCREEN_WIDTH - (LEVEL_SIZE * PATH_OFFSET)

RAYCASTING_DEPTH = 30


SCREEN_MENU = 0
SCREEN_GAME = 1

PLAYER_TEAM = 1
